version: "3"
services:
  nhost:
    image: nhost/nhost:latest
    container_name: nhost
    env_file:
      - .env  # Charge les variables d'environnement depuis le fichier .env
    ports:
      - "1337:1337"
    volumes:
      - ./data:/data
    restart: always
